### ISSUE TITLE
invitations controller broke app

### ISSUE THREAD

**Issue by ciscoLegrand** [ciscoLegrand/cAdmin#8]
``` bash
request: "GET / HTTP/2.0", host: "cappweb.dev"
App 398130 output: Error: The application encountered the following error: expected file /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/bundler/gems/cAdmin-d6d83fe7a3b0/app/controllers/cadmin/users/invitations_controller.rb to define constant Cadmin::Users::InvitationsController, but didn't (Zeitwerk::NameError)
App 398130 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/callbacks.rb:25:in `on_file_autoloaded'
App 398130 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:28:in `require'
App 398130 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
App 398130 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget'
App 398130 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:237:in `block (2 levels) in eager_load'
App 398130 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
App 398130 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
App 398130 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
App 398130 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:232:in `block in eager_load'
App 398130 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `synchronize'
App 398130 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `eager_load'
App 398130 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `each'
App 398130 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `eager_load_all'
App 398130 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/railties-6.1.4.4/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
App 398130 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:32:in `instance_exec'
App 398130 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:32:in `run'
App 398130 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'
App 398130 output:     /home/deploy/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
App 398130 output:     /home/deploy/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
App 398130 output:     /home/deploy/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
App 398130 output:     /home/deploy/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
App 398130 output:     /home/deploy/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `each'
App 398130 output:     /home/deploy/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `call'
App 398130 output:     /home/deploy/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
App 398130 output:     /home/deploy/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
App 398130 output:     /home/deploy/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
App 398130 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:60:in `run_initializers'
App 398130 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/railties-6.1.4.4/lib/rails/application.rb:391:in `initialize!'
App 398130 output:     /home/deploy/cappwedotdev/releases/20220131221259/config/environment.rb:5:in `<top (required)>'
App 398130 output:     config.ru:3:in `require_relative'
App 398130 output:     config.ru:3:in `block in <main>'
App 398130 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 398130 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 398130 output:     config.ru:1:in `new'
App 398130 output:     config.ru:1:in `<main>'
App 398130 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
App 398130 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 398130 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 398130 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
App 398130 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 398130 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 398130 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2022-01-31 22:24:49.2658 394941/To age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/deploy/cappwedotdev/current: The application encountered the following error: expected file /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/bundler/gems/cAdmin-d6d83fe7a3b0/app/controllers/cadmin/users/invitations_controller.rb to define constant Cadmin::Users::InvitationsController, but didn't (Zeitwerk::NameError)
  Error ID: 0618cd62
  Error details saved to: /tmp/passenger-error-IQPUlM.html

[ E 2022-01-31 22:24:49.2744 394941/T9 age/Cor/Con/CheckoutSession.cpp:281 ]: [Client 1-7] Cannot checkout session because a spawning error occurred. The identifier of the error is 0618cd62. Please see earlier logs for details about the error.
App 398263 output: Error: The application encountered the following error: expected file /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/bundler/gems/cAdmin-d6d83fe7a3b0/app/controllers/cadmin/users/invitations_controller.rb to define constant Cadmin::Users::InvitationsController, but didn't (Zeitwerk::NameError)
App 398263 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/callbacks.rb:25:in `on_file_autoloaded'
App 398263 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:28:in `require'
App 398263 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
App 398263 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget'
App 398263 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:237:in `block (2 levels) in eager_load'
App 398263 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
App 398263 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
App 398263 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
App 398263 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:232:in `block in eager_load'
App 398263 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `synchronize'
App 398263 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `eager_load'
App 398263 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `each'
App 398263 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `eager_load_all'
App 398263 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/railties-6.1.4.4/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
App 398263 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:32:in `instance_exec'
App 398263 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:32:in `run'
App 398263 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'
App 398263 output:     /home/deploy/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
App 398263 output:     /home/deploy/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
App 398263 output:     /home/deploy/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
App 398263 output:     /home/deploy/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
App 398263 output:     /home/deploy/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `each'
App 398263 output:     /home/deploy/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `call'
App 398263 output:     /home/deploy/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
App 398263 output:     /home/deploy/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
App 398263 output:     /home/deploy/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
App 398263 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/railties-6.1.4.4/lib/rails/initializable.rb:60:in `run_initializers'
App 398263 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/railties-6.1.4.4/lib/rails/application.rb:391:in `initialize!'
App 398263 output:     /home/deploy/cappwedotdev/releases/20220131221259/config/environment.rb:5:in `<top (required)>'
App 398263 output:     config.ru:3:in `require_relative'
App 398263 output:     config.ru:3:in `block in <main>'
App 398263 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 398263 output:     /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 398263 output:     config.ru:1:in `new'
App 398263 output:     config.ru:1:in `<main>'
App 398263 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
App 398263 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 398263 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 398263 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
App 398263 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 398263 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 398263 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2022-01-31 22:24:51.8334 394941/Tt age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/deploy/cappwedotdev/current: The application encountered the following error: expected file /home/deploy/cappwedotdev/shared/bundle/ruby/2.6.0/bundler/gems/cAdmin-d6d83fe7a3b0/app/controllers/cadmin/users/invitations_controller.rb to define constant Cadmin::Users::InvitationsController, but didn't (Zeitwerk::NameError)
  Error ID: 9817a613
  Error details saved to: /tmp/passenger-error-Z52jMN.html

[ E 2022-01-31 22:24:51.8406 394941/T9 age/Cor/Con/CheckoutSession.cpp:281 ]: [Client 1-8] Cannot checkout session because a spawning error occurred. The identifier of the error is 9817a613. Please see earlier logs for details about the error.
[ E 2022-01-31 22:24:51.8408 394941/T9 age/Cor/Con/CheckoutSession.cpp:281 ]: [Client 1-9] Cannot checkout session because a spawning error occurred. The identifier of the error is 9817a613. Please see earlier logs for details about the error.
```

**Comment by ciscoLegrand** [comment]
'Solution' on commit -> [e24adb1dc7fa7b5](https://github.com/ciscoLegrand/cAdmin/commit/e24adb1dc7fa7b5de3651ccfaa0b49ae085016be)

Avoid using devise_invitable, instead create the user with a password and send a handmade email in Cadmin::UserMailer
